server:
  port: 9001

spring:
  application:
    name: boot-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9100/eureka/


---
spring:
  profiles: develop
server:
  port: 9002

---
spring:
  profiles: product
server:
  port: 9003